name: mon-plugin
version: 1.0-SNAPSHOT
main: com.example.plugin.Main
api-version: 1.20
commands:
  bsl:
    description: Donne la boussole Unclaim Finder
    usage: /bsl
    permission: plugin.admin
permissions:
  plugin.admin:
    description: Permet d'utiliser la commande /bsl
    default: op
  plugin.use.boussole:
    description: Permet d'utiliser la boussole Unclaim Finder
    default: true
description: Un plugin Minecraft de base
author: VotreNom 